### ISSUE TITLE
layer de polígonos contém linhas e pontos

### ISSUE THREAD

**Issue by rpfigueira** [PORBIOTA/PORBIOTA-ICNF#3]
A shapefile do Geocatálogo ICNF __Espécies da fauna - Polígonos (Valores Naturais - Plano Setorial da Rede Natura 2000)__ (https://sig.icnf.pt/portal/home/item.html?id=1a8cf54b3ce843688df52d833bc137e3) contém polígonos, pontos e linhas misturadas. Provalemente houve um problema na criação da layer, tendo sido incluídos pontos baseados em pontos e linha

**Comment by TeresaPimenta** [comment]
O tema **Espécies da fauna - Polígonos (Valores Naturais - Plano Setorial da Rede Natura 2000)** disponível no geocatálogo refere-se apenas a polígonos. Está tal como na sua origem, o Plano Setorial Rede Natura 2000. Resulta da junção (não União) de tudo o que eram polígonos relativos a espécies.
Para tratamento destes dados deve ser criada uma shapefile/tabela para cada espécie. Cada polígono será referenciado com uma coordenada do centroide (real centroid) e a referência ao polígono com o WKT. O WKT é gerado (uma das formas) para todos os polígonos se no QGIS selecionarmos a tabela e fizermos (QGIS3.16-ferramentas da tabela "Copiar linhas selecionadas para área de transferência CTRL+C" e colarmos (paste) num excel.
Atenção que o WKT deve ser gerado com a shapefile no Sistema de referência WGS84 (EPSG 4326) para ficar tudo no mesmo Sistema.

**Comment by rpfigueira** [comment]
> deve ser criada uma shapefile/tabela para cada espécie.

não me parece que seja necessário criar uma shapefile para cada espécie, uma vez que o dataset a publicar irá conter as ocorrências de todas as espécies. Em termos de processamento, será semelhante ao que se fez para o atlas dos répteis e anfíbios

**Comment by TeresaPimenta** [comment]
Certo
